site_name: Acessibilidade Web — Guia de Bolso
site_description: Guia prático alinhado à WCAG 2.2, ABNT NBR 17225/17060 e Gov.br
site_url: https://unb-ihc.github.io/IHC_2026.1_Grupo05
repo_url: https://github.com/UnB-IHC/IHC_2026.1_Grupo05
repo_name: Grupo 05 • IHC 2026.1
edit_uri: ""

theme:
  name: material
  language: pt-BR
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - content.code.copy
    - toc.integrate
    - search.highlight
    - search.suggest
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: deep blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: deep blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Modo claro

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - footnotes
  - def_list
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true

extra_css:
  - stylesheets/extra.css

nav:
  - Início: 
    - Introdução: index.md
    - Para que serve o guia: inicio/paraQueServe.md
  - Guia de Site Acessível: guia/site_acessivel.md
  - WCAG: wcag.md
  - Checklist: 
    - Regras Gerais: checklist/checklist.md
    - Design: design/design.md
    - Desenvolvimento Web: devWeb/non_text_content.md
    - Produção de Conteúdo: geracaoConteudo/conteudo.md
    - Gestão e Governança: checklist/gestao.md
  - Avaliação DETRAN-DF:
      - Relatório de Inspeção: avaliacao/introducao.md
      - Persona de Referência: avaliacao/persona.md
  - Checklist Aplicada: avaliacao/checklistDetran.md
  - Metodologias & Apoio:
      - Ferramentas de Apoio: tools/ferramentas.md
      - Heurísticas de Nielsen: metodo/heuristicas.md
      - Técnicas de IHC: metodo/tecnicasIHC.md
      - Gestão do Projeto: gestaoProjeto/gestaoProjeto.md